<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="$(Microsoft-AspNetCore-TestHost)" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(Microsoft-NET-Test-Sdk)" />
	  <PackageReference Include="xunit" Version="$(xunit)" />
	  <PackageReference Include="xunit.runner.visualstudio" Version="$(xunit-runner-visualstudio)">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\example-api\example-api.csproj" />
    <ProjectReference Include="..\..\src\ParameterStoreConfigurationProvider\ParameterStoreConfigurationProvider.csproj" />
  </ItemGroup>

</Project>
