<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Use AWS ParameterStore to configure your .net core project</Description>
    <PackageProjectUrl>https://github.com/schwamster/ParameterStoreConfigurationProvider</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/schwamster/ParameterStoreConfigurationProvider/blob/master/LICENSE</PackageLicenseUrl>
    <Copyright>Bastian Töpfer</Copyright>
    <PackageTags>AWS ParameterStore Configuration</PackageTags>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="$(AWSSDK-Core)" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="$(AWSSDK-SimpleSystemsManagement)" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="$(Microsoft-Extensions-Configuration)" />
  </ItemGroup>

</Project>
